### ISSUE TITLE
Add Makefile/CMakeLists.txt

### ISSUE THREAD

**Issue by coremedic** [Meowmycks/LetMeowIn#1]
This code is difficult to compile correctly without a Visual Studio project file or a Makefile/CMakeLists.txt file. Would be very helpful if you could add one of these.

**Comment by Meowmycks** [comment]
I have full faith that when you try to use this tool, you come in knowing how to correctly put source code that uses C++ and MASM together into Visual Studio.

If you don't, there's probably more pressing things to worry about. 🙂

**Comment by N00BIER** [comment]
> This code is difficult to compile correctly without a Visual Studio project file or a Makefile/CMakeLists.txt file. Would be very helpful if you could add one of these.

Step 1: Right-click Project -> Build Dependencies->Build customization->masm
Step 2: Right-click .asm file -> Properties->General->Item Type-> Microsoft Macro Assembler
