### ISSUE TITLE
vs2019 compiler error Identifier "REGHANDLE" LetMeowIn not defined Undefined identifier "EventRegister"

### ISSUE THREAD

**Issue by 0xZen-2022** [Meowmycks/LetMeowIn#2]
vs2019 compiler error
Identifier "REGHANDLE" LetMeowIn not defined
Undefined identifier "EventRegister"
I used Google to search for missing winnt.h but added it and still got an error

**Comment by FIendVisions** [comment]
add 
```
#include <evntprov.h>
```
to your project

**Comment by Meowmycks** [comment]
Thanks, good catch. Forgot to add that line back. 👍
